//! Windows APIs, used instead of parsing the console output of `net`,
//! `auditpol` and `netsh`.
//!
//! Every module here is built on the official `windows` crate and compiled only
//! on Windows, which mirrors the C# port: its equivalents live under
//! `Core/Native`, are generated by CsWin32, and are compiled only for the
//! `net10.0-windows` target framework. The call sites in `tasks` select between
//! this and the shell-out path with `#[cfg(windows)]`, exactly as the C# side
//! does with `#if WINDOWS`.
//!
//! The reason for all of it is that the command-line tools print localised,
//! human-formatted tables. A parser written against the English output returns
//! nothing on a non-English image, and "nothing" reads to the caller as "the
//! group is empty" or "the policy is already compliant" rather than as a
//! failure - so the tool reports success having done nothing. These APIs return
//! structured data and a status code, so that confusion cannot arise.

#[cfg(windows)]
pub mod accounts;
#[cfg(windows)]
pub mod audit_policy;
#[cfg(windows)]
pub mod dns;
#[cfg(windows)]
pub mod firewall;
#[cfg(windows)]
pub mod installed_software;
#[cfg(windows)]
pub mod registry;
#[cfg(windows)]
pub mod services;
#[cfg(windows)]
pub mod shares;
#[cfg(windows)]
pub mod users;

/// Encode a Rust string as a null-terminated UTF-16 buffer for the Win32 `W`
/// entry points.
#[cfg(windows)]
pub(crate) fn to_wide(value: &str) -> Vec<u16> {
    value.encode_utf16().chain(std::iter::once(0)).collect()
}

/// Read a null-terminated UTF-16 string returned by Windows.
///
/// # Safety
/// `ptr` must be null or point to a null-terminated UTF-16 string.
#[cfg(windows)]
pub(crate) unsafe fn from_wide(ptr: *const u16) -> Option<String> {
    unsafe {
        if ptr.is_null() {
            return None;
        }
        let mut len = 0usize;
        while *ptr.add(len) != 0 {
            len += 1;
        }
        Some(String::from_utf16_lossy(std::slice::from_raw_parts(
            ptr, len,
        )))
    }
}
