// =============================================================================
// PinnacleCyPat - Password policy (Linux)
// Author: Maxwell McCormick
// Copyright 2026 Maxwell McCormick
// SPDX-License-Identifier: Apache-2.0
// =============================================================================

//! Password complexity, history and lockout - the PAM half of what
//! `net accounts` and `secedit` do on Windows.
//!
//! Linux splits this across three mechanisms, and a run that touches only one
//! of them satisfies none of the scored checks:
//!
//! | Wanted | Where it lives |
//! |---|---|
//! | Length and character classes | `pam_pwquality` |
//! | History (no reuse) | `pam_unix` `remember=` |
//! | Lockout after failed attempts | `pam_faillock` |
//! | Ageing (max/min/warn) | `login.defs`, applied by Security Hardening |
//!
//! The complexity settings are written to `/etc/security/pwquality.conf`
//! rather than as arguments on the `pam_pwquality` line in
//! `common-password`. Both work, but the PAM file is regenerated by
//! `pam-auth-update` whenever a package touches authentication, which silently
//! reverts arguments added there. `pwquality.conf` survives it.
//!
//! `pam_faillock` needs a line in `common-auth`, which has no equivalent
//! standalone file. That edit is made in place, and the module comment on
//! `file_ops` explains why a duplicate definition there is cleaned up rather
//! than tolerated.

use pinnacle_core::models::{SystemInfo, TaskResult};
use pinnacle_core::task::Task;
use pinnacle_core::{impl_task_meta, remediation, ui};

use crate::file_ops::{self, Style};
use async_trait::async_trait;

/// Complexity, read by `pam_pwquality` on every password change.
const PWQUALITY_CONF: &str = "/etc/security/pwquality.conf";

/// Where `pam_faillock` and `pam_unix` are configured.
const COMMON_AUTH: &str = "/etc/pam.d/common-auth";
const COMMON_PASSWORD: &str = "/etc/pam.d/common-password";

/// One complexity setting: the key, the value, and what it buys.
const PWQUALITY: &[(&str, &str, &str)] = &[
    ("minlen", "14", "minimum password length"),
    ("dcredit", "-1", "at least one digit"),
    ("ucredit", "-1", "at least one upper-case letter"),
    ("lcredit", "-1", "at least one lower-case letter"),
    ("ocredit", "-1", "at least one symbol"),
    (
        "difok",
        "4",
        "at least four characters must differ from the old password",
    ),
    (
        "retry",
        "3",
        "attempts allowed before the change is refused",
    ),
    (
        "maxrepeat",
        "3",
        "no more than three identical consecutive characters",
    ),
    (
        "usercheck",
        "1",
        "the password may not contain the account name",
    ),
    (
        "enforcing",
        "1",
        "the rules are enforced rather than merely warned about",
    ),
];

/// How many previous passwords `pam_unix` refuses to accept again.
const REMEMBER: u32 = 5;

/// Failed attempts before `pam_faillock` locks the account, and for how long.
const DENY: u32 = 5;
const UNLOCK_SECONDS: u32 = 900;

pub struct PasswordPolicyTask {
    name: String,
    description: String,
    dry_run: bool,
}

impl PasswordPolicyTask {
    pub fn new() -> Self {
        Self {
            name: "Password Policy".to_string(),
            description: "Complexity, history and lockout, via PAM".to_string(),
            dry_run: false,
        }
    }
}

impl Default for PasswordPolicyTask {
    fn default() -> Self {
        Self::new()
    }
}

/// Is `pam_faillock` configured in the given `common-auth` content?
///
/// Looked for by module name rather than by exact line, because the surrounding
/// arguments differ between distributions and a string comparison would report
/// a correctly configured file as non-compliant and rewrite it every run.
pub fn faillock_configured(common_auth: &str) -> bool {
    common_auth
        .lines()
        .filter(|l| file_ops::is_active(l))
        .any(|l| l.contains("pam_faillock.so"))
}

/// The `remember=` value on the `pam_unix` password line, if there is one.
pub fn remember_value(common_password: &str) -> Option<u32> {
    common_password
        .lines()
        .filter(|l| file_ops::is_active(l))
        .find(|l| l.contains("pam_unix.so"))
        .and_then(|l| {
            l.split_whitespace()
                .find_map(|token| token.strip_prefix("remember="))
        })
        .and_then(|v| v.parse().ok())
}

#[async_trait]
impl Task for PasswordPolicyTask {
    impl_task_meta!();

    async fn read_system_state(&mut self) -> SystemInfo {
        let mut lines = Vec::new();
        for (key, _value, _why) in PWQUALITY {
            let state = file_ops::read(PWQUALITY_CONF, Style::Equals, key)
                .await
                .unwrap_or_else(|| "unreadable".to_string());
            lines.push(format!("{key} = {state}"));
        }
        let auth = tokio::fs::read_to_string(COMMON_AUTH)
            .await
            .unwrap_or_default();
        lines.push(format!("pam_faillock: {}", faillock_configured(&auth)));
        SystemInfo {
            raw_output: Some(lines.join("\n")),
            ..Default::default()
        }
    }

    async fn execute(&mut self) -> TaskResult {
        let mut result = TaskResult {
            task_name: self.name.clone(),
            success: true,
            items_attempted: PWQUALITY.len() as i32 + 2,
            ..Default::default()
        };

        if self.dry_run {
            for (key, value, why) in PWQUALITY {
                let _ = file_ops::set(PWQUALITY_CONF, Style::Equals, key, value, why).await;
            }
            ui::markup_line(&format!(
                "[cyan]Would configure pam_faillock (deny={DENY}, unlock_time={UNLOCK_SECONDS}) \
                 and pam_unix remember={REMEMBER}[/]"
            ));
            result.message = "DRY RUN: no password policy was changed.".to_string();
            return result;
        }

        let mut failures: Vec<String> = Vec::new();
        for (key, value, why) in PWQUALITY {
            match file_ops::set(PWQUALITY_CONF, Style::Equals, key, value, why).await {
                Ok(()) => result.items_succeeded += 1,
                Err(e) => failures.push(format!("{key}: {e}")),
            }
        }

        // --- lockout ---------------------------------------------------------
        //
        // Reported rather than rewritten. `common-auth` is an ordered stack
        // where the position of a line changes what it does, and a `faillock`
        // entry appended after `pam_deny.so` never runs. Getting that wrong
        // locks every account out of the machine, including root - which is
        // unrecoverable inside a competition round. So the task configures the
        // parameters where it safely can, and says plainly when the module
        // itself is missing rather than guessing at where to insert it.
        let auth = tokio::fs::read_to_string(COMMON_AUTH)
            .await
            .unwrap_or_default();
        let has_faillock = faillock_configured(&auth);
        if has_faillock {
            match file_ops::set(
                "/etc/security/faillock.conf",
                Style::Equals,
                "deny",
                &DENY.to_string(),
                "failed attempts before the account locks",
            )
            .await
            {
                Ok(()) => result.items_succeeded += 1,
                Err(e) => failures.push(format!("faillock deny: {e}")),
            }
            if let Err(e) = file_ops::set(
                "/etc/security/faillock.conf",
                Style::Equals,
                "unlock_time",
                &UNLOCK_SECONDS.to_string(),
                "seconds before a locked account unlocks itself",
            )
            .await
            {
                failures.push(format!("faillock unlock_time: {e}"));
            }
        } else {
            ui::markup_line(
                "[yellow]⚠ pam_faillock is not in /etc/pam.d/common-auth. Add it with \
                 `pam-auth-update` rather than by hand - the order of that file decides \
                 whether it locks attackers out or everyone.[/]",
            );
            remediation::record_finding(
                COMMON_AUTH,
                "accounts lock after repeated failed logins",
                false,
                "pam_faillock.so is absent; not inserted automatically, because a line \
                 placed after pam_deny.so locks every account including root",
            );
        }

        // --- history ---------------------------------------------------------
        let password = tokio::fs::read_to_string(COMMON_PASSWORD)
            .await
            .unwrap_or_default();
        let remembered = remember_value(&password);
        remediation::record_finding(
            COMMON_PASSWORD,
            &format!("the last {REMEMBER} passwords cannot be reused"),
            remembered.is_some_and(|r| r >= REMEMBER),
            &match remembered {
                Some(r) => format!("pam_unix has remember={r}"),
                None => "pam_unix has no remember= argument, so any old password may be reused"
                    .to_string(),
            },
        );
        if remembered.is_none_or(|r| r < REMEMBER) {
            ui::markup_line(&format!(
                "[yellow]⚠ Password history is not enforced. Add `remember={REMEMBER}` to the \
                 pam_unix.so line in {COMMON_PASSWORD}.[/]"
            ));
        }

        result.success = failures.is_empty();
        result.message = format!(
            "{} complexity settings applied; lockout {}.",
            result.items_succeeded,
            if has_faillock {
                "configured"
            } else {
                "reported as absent"
            }
        );
        if !failures.is_empty() {
            result.error_details = Some(failures.join("; "));
        }
        result
    }

    async fn verify(&mut self) -> bool {
        for (key, value, _why) in PWQUALITY {
            if file_ops::read(PWQUALITY_CONF, Style::Equals, key)
                .await
                .as_deref()
                != Some(*value)
            {
                return false;
            }
        }
        true
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Real `common-auth` content from Ubuntu 22.04, with and without faillock.
    const WITHOUT: &str = "\
auth    [success=1 default=ignore]      pam_unix.so nullok
auth    requisite                       pam_deny.so
auth    required                        pam_permit.so
";
    const WITH: &str = "\
auth    required                        pam_faillock.so preauth
auth    [success=1 default=ignore]      pam_unix.so nullok
auth    [default=die]                   pam_faillock.so authfail
auth    requisite                       pam_deny.so
";

    #[test]
    fn faillock_is_detected_by_module_name() {
        assert!(!faillock_configured(WITHOUT));
        assert!(faillock_configured(WITH));
    }

    /// A commented-out faillock line does nothing, and treating it as present
    /// would report lockout as configured on a machine with none.
    #[test]
    fn a_commented_faillock_line_does_not_count() {
        assert!(!faillock_configured(
            "# auth required pam_faillock.so preauth\n"
        ));
    }

    #[test]
    fn the_remember_argument_is_read_off_the_pam_unix_line() {
        let text = "password [success=1 default=ignore] pam_unix.so obscure sha512 remember=5\n";
        assert_eq!(remember_value(text), Some(5));
    }

    /// The stock file has no `remember=` at all, which means any previous
    /// password may be set again immediately.
    #[test]
    fn a_missing_remember_argument_reads_as_none() {
        let text = "password [success=1 default=ignore] pam_unix.so obscure yescrypt\n";
        assert_eq!(remember_value(text), None);
    }

    #[test]
    fn complexity_settings_are_complete_and_well_formed() {
        for (key, value, why) in PWQUALITY {
            assert!(!key.is_empty() && !value.is_empty() && !why.is_empty());
            assert!(!key.contains(' '), "{key} is not a pwquality key");
        }
        // The four character-class credits are what a scored check looks at.
        for required in ["minlen", "dcredit", "ucredit", "lcredit", "ocredit"] {
            assert!(
                PWQUALITY.iter().any(|(k, _, _)| *k == required),
                "{required} is missing"
            );
        }
    }

    #[tokio::test]
    async fn a_dry_run_writes_nothing() {
        pinnacle_core::run_log::set_dry_run(true);
        let mut task = PasswordPolicyTask::new();
        task.set_dry_run(true);
        let result = pinnacle_core::ui::capture(task.execute()).await.0;
        pinnacle_core::run_log::set_dry_run(false);
        assert!(result.success);
        assert!(result.message.starts_with("DRY RUN"), "{}", result.message);
        assert!(
            !std::path::Path::new(PWQUALITY_CONF).exists()
                || !std::fs::read_to_string(PWQUALITY_CONF)
                    .unwrap_or_default()
                    .contains("PinnacleCyPat"),
            "the dry run wrote to {PWQUALITY_CONF}"
        );
    }
}
